services:
  zeppelin:
    build: .
    container_name: zeppelin
    ports:
      - "8080:8080"
    environment:
      - SPARK_HOME=/opt/spark
      - PATH=/opt/spark/bin:/opt/spark/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    volumes:
      - ./notebook:/notebook
      - ./logs:/logs
      - ./output:/tmp/sandbox_zeppelin